### ISSUE TITLE
Configurar pisces p100 con firmware Nebra

### ISSUE THREAD

**Issue by Desenlatado** [NebraLtd/helium-pisces#1]
Hola, no se como configurar desde ssh mi hotspot con este firmware. Alguien podría ayudarme para poder hacer que funcione de nuevo?

**Comment by shawaj** [comment]
You can't configure it via ssh unless you add ssh keys to the device...

- https://docs.balena.io/reference/OS/configuration/#sshkeys
- https://docs.balena.io/learn/manage/ssh-access/#add-an-ssh-key-to-balenacloud

Alternatively you can install via the balenaHub at the following link, and use the terminal from BalenaCloud. However you will have to manage your own updates...
https://hub.balena.io/apps/2025889/helium-pisces-app
