### ISSUE TITLE
Radio Operational - False

### ISSUE THREAD

**Issue by vstrong-info** [NebraLtd/helium-pisces#2]
<img width="697" alt="image" src="https://user-images.githubusercontent.com/26736078/224348300-c180b6cc-1178-43f4-a827-ebd067e3fc22.png">
Pisces P100 miner running Nebra firmware through Balena Cloud. It looks like the Packet Forwarder is not working. 
Is there anything we can do? Thank you.
Would someone from Nebra be able to troubleshoot this remotely through Balena Cloud? 
Thank you.

**Comment by shawaj** [comment]
Can you add me to the device / fleet to look at it?

Username gh_shawaj

**Comment by vstrong-info** [comment]
> Can you add me to the device / fleet to look at it?
> 
> Username gh_shawaj
Done.

**Comment by shawaj** [comment]
@vstrong-info can you send the link to the device also?

**Comment by vstrong-info** [comment]
> @vstrong-info can you send the link to the device also?
@shawaj 
https://dashboard.balena-cloud.com/devices/b3877407ccbc3c5453dc2d54fdef87b3

**Comment by shawaj** [comment]
Thanks - last request, can you make me a developer member on the organisation?

Otherwise I can't make any changes to settings to try and fix it unfortunately

**Comment by vstrong-info** [comment]
> Thanks - last request, can you make me a developer member on the organisation?
> 
> Otherwise I can't make any changes to settings to try and fix it unfortunately
Thank you. 
I think it is already configured:
<img width="674" alt="image" src="https://user-images.githubusercontent.com/26736078/227991725-4021f633-a3dc-4c57-b1a8-147fa013e1ce.png">

**Comment by vstrong-info** [comment]
> <img alt="image" width="697" src="https://user-images.githubusercontent.com/26736078/224348300-c180b6cc-1178-43f4-a827-ebd067e3fc22.png">
> 
> Pisces P100 miner running Nebra firmware through Balena Cloud. It looks like the Packet Forwarder is not working. Is there anything we can do? Thank you. Would someone from Nebra be able to troubleshoot this remotely through Balena Cloud? Thank you.

@shawaj I have just updated to 2023.02.07.0-25 (d2dd598) but still getting the same error message.

**Comment by vstrong-info** [comment]
@shawaj I updated this miner to -26 version but could not get the Radio working. Please help.

**Comment by shawaj** [comment]
Let me take a look later on this evening. Sorry I've been very busy the last few weeks. 

It's probably just the incorrect reset pin. But I'm not sure if this is on all pisces devices or just yours.

Don't suppose you have any pictures of the insides?

**Comment by vstrong-info** [comment]
When it was running original Pisces firmware, at one point Packet Forwarder stopped working, but we managed to get it back online. Not sure what we did. I now re-flashed with Nebra firmware and the issue resurfaced.
I do not have a picture but may be able to take one tomorrow but you need to tell me what we are looking for. 
Thank you.

**Comment by shawaj** [comment]
Ah ok, that's interesting. Perhaps there's some power control chip that we didn't know about.

I'll poke around tonight and see what I can find.

Somewhere we have a few Pisces units but can't remember where. I'll see if someone at our warehouse can dig them out as well.

**Comment by vstrong-info** [comment]
Hi @shawaj , any lack with this Pisces miner? Thank you.

**Comment by vstrong-info** [comment]
Hi @shawaj , did you have a change to look into this issue please? Thank you.

**Comment by vstrong-info** [comment]
I re-seated the radio board and it seems to be OK now. I hope this was the issue.

**Comment by shawaj** [comment]
@vstrong-info ah that's great news.

Is it beaconing and witnessing ok?

To be honest I was struggling to find any issue when I had tried a few things on it before.

**Comment by vstrong-info** [comment]
Yes, everything is good now. Thank you.
